name: Build, Test and Publish Package

on:
  push:
    tags: 
      - v*
    branches:
      - main
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_VERSION: '6.0.x'
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        shell: bash
        run: dotnet restore

      - name: Build
        shell: bash
        run: dotnet build --no-restore -c Release

      - name: Test
        shell: bash
        run: dotnet test --no-build --verbosity normal -c Release
        
      - name: Pack Tool 
        shell: bash
        run: dotnet pack --no-build Src/ConsoleTool/Cscli.ConsoleTool.csproj -o nupkg -c Release

      - name: Publish To nuget.org
        shell: bash
        run: dotnet nuget push nupkg/*.nupkg -k $NUGET_TOKEN -s https://api.nuget.org/v3/index.json