name: Build, Test and Publish to Nuget

on: push  

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_VERSION: '6.0.x'
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        shell: bash
        run: dotnet restore

      - name: Build
        shell: bash
        run: dotnet build --no-restore

      - name: Test
        shell: bash
        run: dotnet test --no-build --verbosity normal

      - name: Get pwd for workspace path checking
        shell: bash
        run: pwd
        
      - name: Pack Tool 
        shell: bash
        run: dotnet pack /home/runner/work/cscli/cscli/Src/ConsoleTool/Cscli.ConsoleTool.csproj -o /home/runner/work/cscli/cscli/nupkg -c Release

      - name: Publish To nuget.org
        shell: bash
        run: dotnet nuget push /home/runner/work/cscli/cscli/nupkg/*.nupkg -k $NUGET_TOKEN -s https://api.nuget.org/v3/index.json